import './global.css';
import { Footer } from '../components/layout/footer';

export const metadata = {
  title: 'Welcome to web-react',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
