name: Azure Deployment

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  NX_BRANCH: ${{ github.ref }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_API_APP_NAME }}
  NODE_ENV: production
  PORT: 3000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Deploy API
      - name: Build API
        run: npx nx build api --prod

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          package: ./dist/apps/api

      - name: Azure Logout
        run: az logout
        if: always()
