name: Azure Deployment

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_API_APP_NAME }}
  NODE_ENV: production
  PORT: 3000

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_API_APP_NAME }}
          package: .
          startup-command: 'cd /home/site/wwwroot && npm ci && npx nx build api --prod && cd dist/apps/api && node main'

      - name: Azure Logout
        run: az logout
        if: always()
