name: Azure Deployment

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  NX_BRANCH: ${{ github.ref }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_API_APP_NAME }}
  NODE_ENV: production
  PORT: 3000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Install NX CLI
        run: npm install -g nx

      - name: Build API
        run: npm run build:api

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./dist/apps/api

      - name: Azure Logout
        run: az logout
        if: always()
